// Code generated by clink-generator; DO NOT EDIT.
package main

import (
	"context"
	"fmt"
	"time"

	"github.com/raymondtc/clink-cli/pkg/generated"
	"github.com/raymondtc/clink-cli/pkg/renderer"
	"github.com/spf13/cobra"
)

var pauseFlags struct {
	agent   string
	typeVal int
	reason  string
}

var pauseCmd = &cobra.Command{
	Use:   "pause",
	Short: "座席置忙",
	RunE:  runpause,
}

func init() {
	agentCmd.AddCommand(pauseCmd)

	pauseCmd.Flags().StringVarP(&pauseFlags.agent, "agent", "a", "", "座席号")
	pauseCmd.MarkFlagRequired("agent")

	pauseCmd.Flags().IntVarP(&pauseFlags.typeVal, "type", "t", 1, "忙碌类型")

	pauseCmd.Flags().StringVarP(&pauseFlags.reason, "reason", "r", "", "忙碌原因")
}

func runpause(cmd *cobra.Command, args []string) error {
	_ = fmt.Sprintf("")
	_ = time.Now()
	_ = context.Background
	_ = generated.CallResult{}
	_ = renderer.Table{}
	api, err := createAPI()
	if err != nil {
		return err
	}
	ctx := context.Background()

	err = api.Pause(ctx, pauseFlags.agent, pauseFlags.typeVal, pauseFlags.reason)
	if err != nil {
		return err
	}
	renderer.PrintSuccess("座席置忙成功")
	return nil
}

var readyFlags struct {
	agent string
}

var readyCmd = &cobra.Command{
	Use:   "ready",
	Short: "座席置闲",
	RunE:  runready,
}

func init() {
	agentCmd.AddCommand(readyCmd)

	readyCmd.Flags().StringVarP(&readyFlags.agent, "agent", "a", "", "座席号")
	readyCmd.MarkFlagRequired("agent")
}

func runready(cmd *cobra.Command, args []string) error {
	_ = fmt.Sprintf("")
	_ = time.Now()
	_ = context.Background
	_ = generated.CallResult{}
	_ = renderer.Table{}
	api, err := createAPI()
	if err != nil {
		return err
	}
	ctx := context.Background()

	err = api.Unpause(ctx, readyFlags.agent)
	if err != nil {
		return err
	}
	renderer.PrintSuccess("座席置闲成功")
	return nil
}

var onlineFlags struct {
	agent    string
	queue    string
	tel      string
	bindType int
}

var onlineCmd = &cobra.Command{
	Use:   "online",
	Short: "座席登录上线",
	RunE:  runonline,
}

func init() {
	agentCmd.AddCommand(onlineCmd)

	onlineCmd.Flags().StringVarP(&onlineFlags.agent, "agent", "a", "", "座席号")
	onlineCmd.MarkFlagRequired("agent")

	onlineCmd.Flags().StringVarP(&onlineFlags.queue, "queue", "q", "", "登录队列号")

	onlineCmd.Flags().StringVar(&onlineFlags.tel, "tel", "", "绑定电话号码")

	onlineCmd.Flags().IntVar(&onlineFlags.bindType, "bind-type", 1, "绑定类型 (1-分机, 2-直线, 3-软电话)")
}

func runonline(cmd *cobra.Command, args []string) error {
	_ = fmt.Sprintf("")
	_ = time.Now()
	_ = context.Background
	_ = generated.CallResult{}
	_ = renderer.Table{}
	api, err := createAPI()
	if err != nil {
		return err
	}
	ctx := context.Background()

	err = api.Online(ctx, onlineFlags.agent, onlineFlags.queue, onlineFlags.tel, onlineFlags.bindType)
	if err != nil {
		return err
	}
	renderer.PrintSuccess("座席登录上线成功")
	return nil
}

var offlineFlags struct {
	agent string
}

var offlineCmd = &cobra.Command{
	Use:   "offline",
	Short: "座席登出下线",
	RunE:  runoffline,
}

func init() {
	agentCmd.AddCommand(offlineCmd)

	offlineCmd.Flags().StringVarP(&offlineFlags.agent, "agent", "a", "", "座席号")
	offlineCmd.MarkFlagRequired("agent")
}

func runoffline(cmd *cobra.Command, args []string) error {
	_ = fmt.Sprintf("")
	_ = time.Now()
	_ = context.Background
	_ = generated.CallResult{}
	_ = renderer.Table{}
	api, err := createAPI()
	if err != nil {
		return err
	}
	ctx := context.Background()

	err = api.Offline(ctx, offlineFlags.agent)
	if err != nil {
		return err
	}
	renderer.PrintSuccess("座席登出下线成功")
	return nil
}
