// Code generated by clink-generator; DO NOT EDIT.
package main

import (
	"context"
	"fmt"
	"time"

	"github.com/raymondtc/clink-cli/pkg/generated"
	"github.com/raymondtc/clink-cli/pkg/renderer"
	"github.com/spf13/cobra"
)

var agentsFlags struct {
	agent string
}

var agentsCmd = &cobra.Command{
	Use:   "agents",
	Short: "查询座席状态列表",
	RunE:  runagents,
}

func init() {

	agentsCmd.Flags().StringVarP(&agentsFlags.agent, "agent", "a", "", "座席号 (可选，不传则查询所有)")
}

func runagents(cmd *cobra.Command, args []string) error {
	_ = fmt.Sprintf("")
	_ = time.Now()
	_ = context.Background
	_ = generated.CallResult{}
	_ = renderer.Table{}
	api, err := createAPI()
	if err != nil {
		return err
	}
	ctx := context.Background()

	agents, _, err := api.ListAgentStatus(ctx, agentsFlags.agent)
	if err != nil {
		return err
	}
	return renderOutput(agents)
}
