// Code generated by clink-generator; DO NOT EDIT.
package main

import (
	"context"
	"fmt"
	"time"

	"github.com/raymondtc/clink-cli/pkg/generated"
	"github.com/raymondtc/clink-cli/pkg/renderer"
	"github.com/spf13/cobra"
)

var agentsFlags struct {
	agent string
}

var agentsCmd = &cobra.Command{
	Use:   "agents",
	Short: "查询座席状态列表",
	RunE:  runagents,
}

func init() {

	agentsCmd.Flags().StringVarP(&agentsFlags.agent, "agent", "a", "", "座席号 (可选，不传则查询所有)")
}

func runagents(cmd *cobra.Command, args []string) error {
	_ = fmt.Sprintf("")
	_ = time.Now()
	_ = context.Background
	_ = generated.CallResult{}
	_ = renderer.Table{}
	api, err := createAPI()
	if err != nil {
		return err
	}
	ctx := context.Background()

	agents, err := api.GetAgentStatus(ctx, agentsFlags.agent)
	if err != nil {
		return err
	}
	if outputFormat == "table" {
		fmt.Printf("座席列表 (%d 人):\n\n", len(agents))
		table := &renderer.Table{
			Headers: []string{"状态", "姓名", "座席号", "状态"},
		}
		for _, agent := range agents {
			statusIcon := "⚪"
			status := deref(agent.AgentStatus)
			switch status {
			case "空闲":
				statusIcon = "🟢"
			case "置忙":
				statusIcon = "🔴"
			case "离线":
				statusIcon = "⚪"
			}
			table.Rows = append(table.Rows, renderer.Row{
				Cells: []renderer.Cell{
					{Value: statusIcon},
					{Value: deref(agent.ClientName)},
					{Value: deref(agent.Cno)},
					{Value: status},
				},
			})
		}
		r := renderer.New(renderer.FormatTable)
		return r.Render(table)
	}
	return renderOutput(agents)
}
