// Code generated by clink-generator; DO NOT EDIT.
package main

import (
	"context"
	"fmt"
	"time"

	"github.com/raymondtc/clink-cli/pkg/generated"
	"github.com/raymondtc/clink-cli/pkg/renderer"
	"github.com/spf13/cobra"
)

var webcallFlags struct {
	clid      string
	ivr       string
	requestId string
	agent     string
}

var webcallCmd = &cobra.Command{
	Use:   "call webcall <phone>",
	Short: "发起 WebCall 外呼",
	Args:  cobra.ExactArgs(1),
	RunE:  runwebcall,
}

func init() {
	callCmd.AddCommand(webcallCmd)

	webcallCmd.Flags().StringVar(&webcallFlags.clid, "clid", "", "外显号码")

	webcallCmd.Flags().StringVar(&webcallFlags.ivr, "ivr", "工作时间", "IVR流程名称")

	webcallCmd.Flags().StringVar(&webcallFlags.requestId, "request-id", "", "请求唯一ID (防重放)")

	webcallCmd.Flags().StringVarP(&webcallFlags.agent, "agent", "a", "", "座席号 (指定后使用座席外呼)")
}

func runwebcall(cmd *cobra.Command, args []string) error {
	_ = fmt.Sprintf("")
	_ = time.Now()
	_ = context.Background
	_ = generated.CallResult{}
	_ = renderer.Table{}
	api, err := createAPI()
	if err != nil {
		return err
	}
	ctx := context.Background()
	phone := args[0]

	renderer.PrintSuccess("使用 WebCall 发起呼叫（无需座席）...")
	resp, err := api.Webcall(ctx, phone, webcallFlags.clid, webcallFlags.ivr, webcallFlags.requestId)
	if err != nil {
		return err
	}
	_ = resp
	fmt.Println()
	renderer.PrintKV(map[string]string{
		"状态": "submitted",
		"号码": phone,
	})
	return nil
}

var hangupFlags struct {
	agent string
}

var hangupCmd = &cobra.Command{
	Use:   "hangup",
	Short: "挂断当前通话",
	RunE:  runhangup,
}

func init() {
	callCmd.AddCommand(hangupCmd)

	hangupCmd.Flags().StringVarP(&hangupFlags.agent, "agent", "a", "", "座席号")
	hangupCmd.MarkFlagRequired("agent")
}

func runhangup(cmd *cobra.Command, args []string) error {
	_ = fmt.Sprintf("")
	_ = time.Now()
	_ = context.Background
	_ = generated.CallResult{}
	_ = renderer.Table{}
	api, err := createAPI()
	if err != nil {
		return err
	}
	ctx := context.Background()

	_, err = api.Unlink(ctx, hangupFlags.agent)
	if err != nil {
		return err
	}
	renderer.PrintSuccess("挂断当前通话成功")
	return nil
}

var holdFlags struct {
	agent string
}

var holdCmd = &cobra.Command{
	Use:   "hold",
	Short: "保持当前通话",
	RunE:  runhold,
}

func init() {
	callCmd.AddCommand(holdCmd)

	holdCmd.Flags().StringVarP(&holdFlags.agent, "agent", "a", "", "座席号")
	holdCmd.MarkFlagRequired("agent")
}

func runhold(cmd *cobra.Command, args []string) error {
	_ = fmt.Sprintf("")
	_ = time.Now()
	_ = context.Background
	_ = generated.CallResult{}
	_ = renderer.Table{}
	api, err := createAPI()
	if err != nil {
		return err
	}
	ctx := context.Background()

	_, err = api.Hold(ctx, holdFlags.agent)
	if err != nil {
		return err
	}
	renderer.PrintSuccess("保持当前通话成功")
	return nil
}

var unholdFlags struct {
	agent string
}

var unholdCmd = &cobra.Command{
	Use:   "unhold",
	Short: "恢复保持的通话",
	RunE:  rununhold,
}

func init() {
	callCmd.AddCommand(unholdCmd)

	unholdCmd.Flags().StringVarP(&unholdFlags.agent, "agent", "a", "", "座席号")
	unholdCmd.MarkFlagRequired("agent")
}

func rununhold(cmd *cobra.Command, args []string) error {
	_ = fmt.Sprintf("")
	_ = time.Now()
	_ = context.Background
	_ = generated.CallResult{}
	_ = renderer.Table{}
	api, err := createAPI()
	if err != nil {
		return err
	}
	ctx := context.Background()

	_, err = api.Unhold(ctx, unholdFlags.agent)
	if err != nil {
		return err
	}
	renderer.PrintSuccess("恢复保持的通话成功")
	return nil
}

var transferFlags struct {
	agent   string
	typeVal int
	target  string
}

var transferCmd = &cobra.Command{
	Use:   "transfer",
	Short: "转接电话",
	RunE:  runtransfer,
}

func init() {
	callCmd.AddCommand(transferCmd)

	transferCmd.Flags().StringVarP(&transferFlags.agent, "agent", "a", "", "座席号")
	transferCmd.MarkFlagRequired("agent")

	transferCmd.Flags().IntVarP(&transferFlags.typeVal, "type", "t", 0, "转接类型 (1-座席, 2-队列, 3-外线)")
	transferCmd.MarkFlagRequired("type")

	transferCmd.Flags().StringVar(&transferFlags.target, "target", "", "转接目标")
	transferCmd.MarkFlagRequired("target")
}

func runtransfer(cmd *cobra.Command, args []string) error {
	_ = fmt.Sprintf("")
	_ = time.Now()
	_ = context.Background
	_ = generated.CallResult{}
	_ = renderer.Table{}
	api, err := createAPI()
	if err != nil {
		return err
	}
	ctx := context.Background()

	_, err = api.Transfer(ctx, transferFlags.agent, transferFlags.typeVal, transferFlags.target)
	if err != nil {
		return err
	}
	renderer.PrintSuccess("转接电话成功")
	return nil
}
