// Code generated by generate-cli-v3; DO NOT EDIT.
package main

import (
	"fmt"
	"time"

	"github.com/spf13/cobra"
)

var transferFlags struct {
	Cno string
	TransferType string
	TransferObject string
}

var transferCmd = &cobra.Command{
	Use:   "transfer",
	Short: "Transfer",
	Aliases: []string{"xfer"},
	RunE:  runTransfer,
}

func init() {
	callCmd.AddCommand(transferCmd)

	transferCmd.Flags().StringVarP(&transferFlags.TransferType, "type", "t", "", "transferType")
	transferCmd.MarkFlagRequired("type")
	transferCmd.Flags().StringVar(&transferFlags.TransferObject, "target", "", "transferObject")
	transferCmd.MarkFlagRequired("target")
	transferCmd.Flags().StringVarP(&transferFlags.Cno, "agent", "a", "", "座席号")
	transferCmd.MarkFlagRequired("agent")
}

func runTransfer(cmd *cobra.Command, args []string) error {
	fmt.Sprintf("")
	_ = time.Now()
	api, err := createAPI()
	if err != nil {
		return err
	}
	_ = api
	fmt.Println("TODO: Implement API call")
	return nil
}

var unholdFlags struct {
	Cno string
}

var unholdCmd = &cobra.Command{
	Use:   "unhold",
	Short: "Unhold",
	RunE:  runUnhold,
}

func init() {
	callCmd.AddCommand(unholdCmd)

	unholdCmd.Flags().StringVarP(&unholdFlags.Cno, "agent", "a", "", "座席号")
	unholdCmd.MarkFlagRequired("agent")
}

func runUnhold(cmd *cobra.Command, args []string) error {
	fmt.Sprintf("")
	_ = time.Now()
	api, err := createAPI()
	if err != nil {
		return err
	}
	_ = api
	fmt.Println("TODO: Implement API call")
	return nil
}

var webcallFlags struct {
	CustomerNumber string
	Clid string
	IvrName string
}

var webcallCmd = &cobra.Command{
	Use:   "call <phone>",
	Short: "Webcall",
	Aliases: []string{"c", "dial"},
	Args:  cobra.ExactArgs(1),
	RunE:  runWebcall,
}

func init() {
	callCmd.AddCommand(webcallCmd)

	webcallCmd.Flags().StringVar(&webcallFlags.CustomerNumber, "customernumber", "", "客户号码")
	webcallCmd.Flags().StringVar(&webcallFlags.Clid, "caller", "", "clid")
	webcallCmd.Flags().StringVar(&webcallFlags.IvrName, "ivr", "工作时间", "ivrName")
}

func runWebcall(cmd *cobra.Command, args []string) error {
	fmt.Sprintf("")
	_ = time.Now()
	api, err := createAPI()
	if err != nil {
		return err
	}
	_ = api
	// Dangerous operation confirmation
	fmt.Printf("⚠️  确定要呼叫 {phone} 吗？ [y/N]: ")
	fmt.Println("TODO: Implement API call")
	return nil
}

var unlinkFlags struct {
	Cno string
}

var unlinkCmd = &cobra.Command{
	Use:   "hangup",
	Short: "Unlink",
	Aliases: []string{"hup", "end"},
	RunE:  runUnlink,
}

func init() {
	callCmd.AddCommand(unlinkCmd)

	unlinkCmd.Flags().StringVarP(&unlinkFlags.Cno, "agent", "a", "", "座席号")
	unlinkCmd.MarkFlagRequired("agent")
}

func runUnlink(cmd *cobra.Command, args []string) error {
	fmt.Sprintf("")
	_ = time.Now()
	api, err := createAPI()
	if err != nil {
		return err
	}
	_ = api
	fmt.Println("TODO: Implement API call")
	return nil
}

var holdFlags struct {
	Cno string
}

var holdCmd = &cobra.Command{
	Use:   "hold",
	Short: "Hold",
	RunE:  runHold,
}

func init() {
	callCmd.AddCommand(holdCmd)

	holdCmd.Flags().StringVarP(&holdFlags.Cno, "agent", "a", "", "座席号")
	holdCmd.MarkFlagRequired("agent")
}

func runHold(cmd *cobra.Command, args []string) error {
	fmt.Sprintf("")
	_ = time.Now()
	api, err := createAPI()
	if err != nil {
		return err
	}
	_ = api
	fmt.Println("TODO: Implement API call")
	return nil
}

var calloutFlags struct {
	Cno string
	CustomerNumber string
}

var calloutCmd = &cobra.Command{
	Use:   "agent <phone> <agent>",
	Short: "Callout",
	Aliases: []string{"outbound"},
	Args:  cobra.ExactArgs(2),
	RunE:  runCallout,
}

func init() {
	callCmd.AddCommand(calloutCmd)

	calloutCmd.Flags().StringVar(&calloutFlags.CustomerNumber, "customernumber", "", "客户号码")
	calloutCmd.Flags().StringVar(&calloutFlags.Cno, "cno", "", "座席号")
}

func runCallout(cmd *cobra.Command, args []string) error {
	fmt.Sprintf("")
	_ = time.Now()
	api, err := createAPI()
	if err != nil {
		return err
	}
	_ = api
	// Dangerous operation confirmation
	fmt.Printf("⚠️  确定要使用座席 {agent} 外呼 {phone} 吗？ [y/N]: ")
	fmt.Println("TODO: Implement API call")
	return nil
}

