// Code generated by clink-generator; DO NOT EDIT.
package main

import (
	"context"
	"fmt"
	"time"

	"github.com/raymondtc/clink-cli/pkg/generated"
	"github.com/raymondtc/clink-cli/pkg/renderer"
	"github.com/spf13/cobra"
)



var statusFlags struct {
	queue string
}

var statusCmd = &cobra.Command{
	Use:   "status",
	Short: "查询队列状态",
	RunE:  runstatus,
}

func init() {
	queueCmd.AddCommand(statusCmd)

	statusCmd.Flags().StringVarP(&statusFlags.queue, "queue", "q", "", "队列号")
}

func runstatus(cmd *cobra.Command, args []string) error {
	_ = fmt.Sprintf("")
	_ = time.Now()
	_ = context.Background
	_ = generated.CallResult{}
	_ = renderer.Table{}
	api, err := createAPI()
	if err != nil {
		return err
	}
	ctx := context.Background()

	queue, err := api.GetQueueStatus(ctx, statusFlags.queue)
	if err != nil {
		return err
	}
	qname := deref(queue.Qname)
	queueID := deref(queue.Qno)
	if outputFormat == "table" {
		fmt.Printf("队列: %s (%s)\n\n", qname, queueID)
		renderer.PrintKV(map[string]string{
			"等待人数": derefInt(queue.WaitCount),
			"平均等待": fmt.Sprintf("%s 秒", derefInt(queue.QueueUpWaitTime)),
			"在线座席": derefInt(queue.OnlineAgentCount),
			"忙碌座席": derefInt(queue.BusyAgentCount),
		})
		return nil
	}
	return renderOutput(queue)
}



var listFlags struct {
	offset int
	limit int
}

var listCmd = &cobra.Command{
	Use:   "list",
	Short: "查询队列列表",
	RunE:  runlist,
}

func init() {
	queueCmd.AddCommand(listCmd)

	listCmd.Flags().IntVar(&listFlags.offset, "offset", 0, "偏移量")

	listCmd.Flags().IntVar(&listFlags.limit, "limit", 10, "查询条数")
}

func runlist(cmd *cobra.Command, args []string) error {
	_ = fmt.Sprintf("")
	_ = time.Now()
	_ = context.Background
	_ = generated.CallResult{}
	_ = renderer.Table{}
	api, err := createAPI()
	if err != nil {
		return err
	}
	ctx := context.Background()

	queues, err := api.ListQueues(ctx, listFlags.offset, listFlags.limit)
	if err != nil {
		return err
	}
	return renderOutput(queues)
}

