// Code generated by generate-cli-v3; DO NOT EDIT.
package main

import (
	"context"
	"fmt"

	"github.com/spf13/cobra"
)

var queuestatusFlags struct {
	Qnos string
}

var queuestatusCmd = &cobra.Command{
	Use:   "status",
	Short: "QueueStatus",
	Aliases: []string{"qs"},
	RunE:  runQueueStatus,
}

func init() {
	queueCmd.AddCommand(queuestatusCmd)

	queuestatusCmd.Flags().StringVarP(&queuestatusFlags.Qnos, "queue", "q", "", "qnos")
}

func runQueueStatus(cmd *cobra.Command, args []string) error {
	_ = fmt.Sprintf("")
	api, err := createAPI()
	if err != nil {
		return err
	}
	_ = api
	ctx := context.Background()
	_ = ctx

	queues, total, err := api.GetQueueStatus(ctx, queuestatusFlags.Qnos)
	if err != nil {
		return err
	}

	return renderList(queues, total)
	return nil
}

var listqueuesFlags struct {
	Offset int
	StartTime string
	EndTime string
	CustomerNumber string
	Cno string
	Limit int
}

var listqueuesCmd = &cobra.Command{
	Use:   "list",
	Short: "ListQueues",
	Aliases: []string{"ql"},
	RunE:  runListQueues,
}

func init() {
	queueCmd.AddCommand(listqueuesCmd)

	listqueuesCmd.Flags().StringVarP(&listqueuesFlags.StartTime, "start", "s", "7d", "开始时间")
	listqueuesCmd.Flags().StringVarP(&listqueuesFlags.EndTime, "end", "e", "now", "结束时间")
	listqueuesCmd.Flags().StringVarP(&listqueuesFlags.CustomerNumber, "phone", "p", "", "客户号码")
	listqueuesCmd.Flags().StringVarP(&listqueuesFlags.Cno, "agent", "a", "", "座席号")
	listqueuesCmd.Flags().IntVar(&listqueuesFlags.Limit, "limit", 20, "limit")
	listqueuesCmd.Flags().IntVar(&listqueuesFlags.Offset, "offset", 0, "offset")
}

func runListQueues(cmd *cobra.Command, args []string) error {
	_ = fmt.Sprintf("")
	api, err := createAPI()
	if err != nil {
		return err
	}
	_ = api
	ctx := context.Background()
	_ = ctx

	queues, total, err := api.ListQueues(ctx, 0, 10)
	if err != nil {
		return err
	}

	return renderList(queues, total)
	return nil
}

