// Code generated by clink-generator; DO NOT EDIT.
package main

import (
	"context"
	"fmt"
	"time"

	"github.com/raymondtc/clink-cli/pkg/generated"
	"github.com/raymondtc/clink-cli/pkg/renderer"
	"github.com/spf13/cobra"
)

var statusFlags struct {
	queue string
}

var statusCmd = &cobra.Command{
	Use:   "status",
	Short: "查询队列状态",
	RunE:  runstatus,
}

func init() {
	queueCmd.AddCommand(statusCmd)

	statusCmd.Flags().StringVarP(&statusFlags.queue, "queue", "q", "", "队列号")
}

func runstatus(cmd *cobra.Command, args []string) error {
	_ = fmt.Sprintf("")
	_ = time.Now()
	_ = context.Background
	_ = generated.CallResult{}
	_ = renderer.Table{}
	api, err := createAPI()
	if err != nil {
		return err
	}
	ctx := context.Background()

	queues, _, err := api.GetQueueStatus(ctx, statusFlags.queue)
	if err != nil {
		return err
	}
	if len(queues) == 0 {
		return fmt.Errorf("未找到队列")
	}
	queue := queues[0]
	qname := ""
	if v, ok := queue["qname"].(string); ok {
		qname = v
	}
	queueID := ""
	if v, ok := queue["qno"].(string); ok {
		queueID = v
	}
	if outputFormat == "table" {
		fmt.Printf("队列: %s (%s)\n\n", qname, queueID)
		waitCount := 0
		if v, ok := queue["waitCount"].(float64); ok {
			waitCount = int(v)
		}
		waitTime := 0
		if v, ok := queue["queueUpWaitTime"].(float64); ok {
			waitTime = int(v)
		}
		onlineCount := 0
		if v, ok := queue["onlineAgentCount"].(float64); ok {
			onlineCount = int(v)
		}
		busyCount := 0
		if v, ok := queue["busyAgentCount"].(float64); ok {
			busyCount = int(v)
		}
		renderer.PrintKV(map[string]string{
			"等待人数": fmt.Sprintf("%d", waitCount),
			"平均等待": fmt.Sprintf("%d 秒", waitTime),
			"在线座席": fmt.Sprintf("%d", onlineCount),
			"忙碌座席": fmt.Sprintf("%d", busyCount),
		})
		return nil
	}
	return renderOutput(queues)
}

var listFlags struct {
	offset int
	limit  int
}

var listCmd = &cobra.Command{
	Use:   "list",
	Short: "查询队列列表",
	RunE:  runlist,
}

func init() {
	queueCmd.AddCommand(listCmd)

	listCmd.Flags().IntVar(&listFlags.offset, "offset", 0, "偏移量")

	listCmd.Flags().IntVar(&listFlags.limit, "limit", 10, "查询条数")
}

func runlist(cmd *cobra.Command, args []string) error {
	_ = fmt.Sprintf("")
	_ = time.Now()
	_ = context.Background
	_ = generated.CallResult{}
	_ = renderer.Table{}
	api, err := createAPI()
	if err != nil {
		return err
	}
	ctx := context.Background()

	queues, _, err := api.ListQueues(ctx, listFlags.limit, listFlags.offset)
	if err != nil {
		return err
	}
	return renderOutput(queues)
}
