// Code generated by clink-generator; DO NOT EDIT.
package main

import (
	"context"
	"fmt"
	"time"

	"github.com/raymondtc/clink-cli/pkg/generated"
	"github.com/raymondtc/clink-cli/pkg/renderer"
	"github.com/spf13/cobra"
)

// parseDateRange converts date strings (YYYY-MM-DD) to Unix second timestamps.
// start is treated as 00:00:00, end as 23:59:59.
func parseDateRange(startDate, endDate string) (int64, int64, error) {
	loc, _ := time.LoadLocation("Asia/Shanghai")
	start, err := time.ParseInLocation("2006-01-02", startDate, loc)
	if err != nil {
		return 0, 0, fmt.Errorf("invalid start date %q: %w", startDate, err)
	}
	end, err := time.ParseInLocation("2006-01-02", endDate, loc)
	if err != nil {
		return 0, 0, fmt.Errorf("invalid end date %q: %w", endDate, err)
	}
	end = end.Add(23*time.Hour + 59*time.Minute + 59*time.Second)
	return start.Unix(), end.Unix(), nil
}

var inboundFlags struct {
	start  string
	end    string
	phone  string
	agent  string
	offset int
	limit  int
}

var inboundCmd = &cobra.Command{
	Use:   "inbound",
	Short: "查询呼入通话记录",
	RunE:  runinbound,
}

func init() {
	recordsCmd.AddCommand(inboundCmd)

	inboundCmd.Flags().StringVarP(&inboundFlags.start, "start", "s", time.Now().AddDate(0, 0, -7).Format("2006-01-02"), "开始时间 (YYYY-MM-DD)")

	inboundCmd.Flags().StringVarP(&inboundFlags.end, "end", "e", time.Now().Format("2006-01-02"), "结束时间 (YYYY-MM-DD)")

	inboundCmd.Flags().StringVarP(&inboundFlags.phone, "phone", "p", "", "客户号码筛选")

	inboundCmd.Flags().StringVarP(&inboundFlags.agent, "agent", "a", "", "座席号筛选")

	inboundCmd.Flags().IntVar(&inboundFlags.offset, "offset", 0, "偏移量")

	inboundCmd.Flags().IntVar(&inboundFlags.limit, "limit", 10, "查询条数 (10-100)")
}

func runinbound(cmd *cobra.Command, args []string) error {
	_ = fmt.Sprintf("")
	_ = generated.CallResult{}
	_ = renderer.Table{}
	api, err := createAPI()
	if err != nil {
		return err
	}
	ctx := context.Background()

	startTime, endTime, err := parseDateRange(inboundFlags.start, inboundFlags.end)
	if err != nil {
		return err
	}
	records, total, err := api.ListCdrIbs(ctx, startTime, endTime, inboundFlags.offset, inboundFlags.limit, inboundFlags.phone, inboundFlags.agent)
	if err != nil {
		return err
	}
	return renderList(records, total)
}

var outboundFlags struct {
	start  string
	end    string
	phone  string
	agent  string
	offset int
	limit  int
}

var outboundCmd = &cobra.Command{
	Use:   "outbound",
	Short: "查询外呼通话记录",
	RunE:  runoutbound,
}

func init() {
	recordsCmd.AddCommand(outboundCmd)

	outboundCmd.Flags().StringVarP(&outboundFlags.start, "start", "s", time.Now().AddDate(0, 0, -7).Format("2006-01-02"), "开始时间")

	outboundCmd.Flags().StringVarP(&outboundFlags.end, "end", "e", time.Now().Format("2006-01-02"), "结束时间")

	outboundCmd.Flags().StringVarP(&outboundFlags.phone, "phone", "p", "", "客户号码筛选")

	outboundCmd.Flags().StringVarP(&outboundFlags.agent, "agent", "a", "", "座席号筛选")

	outboundCmd.Flags().IntVar(&outboundFlags.offset, "offset", 0, "")

	outboundCmd.Flags().IntVar(&outboundFlags.limit, "limit", 10, "")
}

func runoutbound(cmd *cobra.Command, args []string) error {
	_ = fmt.Sprintf("")
	_ = generated.CallResult{}
	_ = renderer.Table{}
	api, err := createAPI()
	if err != nil {
		return err
	}
	ctx := context.Background()

	startTime, endTime, err := parseDateRange(outboundFlags.start, outboundFlags.end)
	if err != nil {
		return err
	}
	records, total, err := api.ListCdrObs(ctx, startTime, endTime, outboundFlags.offset, outboundFlags.limit, outboundFlags.phone, outboundFlags.agent)
	if err != nil {
		return err
	}
	return renderList(records, total)
}
