// Code generated by generate-cli-v3; DO NOT EDIT.
package main

import "github.com/spf13/cobra"


var agentsCmd = &cobra.Command{
	Use:   "agents",
	Short: "agents related commands",
}

var callCmd = &cobra.Command{
	Use:   "call",
	Short: "call related commands",
}

var queueCmd = &cobra.Command{
	Use:   "queue",
	Short: "queue related commands",
}

var recordsCmd = &cobra.Command{
	Use:   "records",
	Short: "records related commands",
}


func init() {
	rootCmd.AddCommand(agentsCmd)
	rootCmd.AddCommand(callCmd)
	rootCmd.AddCommand(queueCmd)
	rootCmd.AddCommand(recordsCmd)
}
