// Code generated by api-generator; DO NOT EDIT.

package api

import (
	"context"
	"fmt"

	"github.com/raymondtc/clink-cli/pkg/generated"
)

// DescribeRecordFileUrl - 查询通话录音地址
func (a *GeneratedAPI) DescribeRecordFileUrl(ctx context.Context, callId string, recordSide int, timeout int, download int) (map[string]interface{}, error) {
	params := &generated.DescribeRecordFileUrlParams{}
	// 注意：需要根据实际生成的类型字段调整
	_ = callId
	_ = recordSide
	_ = timeout
	_ = download

	resp, err := a.client.DescribeRecordFileUrlWithResponse(ctx, params)
	if err != nil {
		return nil, fmt.Errorf("describeRecordFileUrl: %w", err)
	}

	if resp.JSON200 == nil {
		return nil, fmt.Errorf("unexpected response status: %d", resp.StatusCode())
	}

	// 返回包含 URL 的 map
	result := map[string]interface{}{
		"data": resp.JSON200,
	}
	return result, nil
}
