// cli_generator.go - CLI code generator from OpenAPI spec
// Generates cobra commands and flags from OpenAPI parameters
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"gopkg.in/yaml.v3"
)

// CLICommand represents a CLI command generated from OpenAPI operation
type CLICommand struct {
	Name        string
	Use         string
	Short       string
	Long        string
	HTTPMethod  string
	Path        string
	Flags       []CLIFlag
	Args        []CLIArg
	HasBody     bool
	BodyFields  []BodyField
}

// CLIFlag represents a command flag
type CLIFlag struct {
	Name        string
	Shorthand   string
	Type        string
	Default     string
	Description string
	Required    bool
}

// CLIArg represents a positional argument
type CLIArg struct {
	Name     string
	Type     string
	Required bool
}

// BodyField represents a field in request body
type BodyField struct {
	Name     string
	Type     string
	Required bool
}

// CLIGenerator generates CLI code from OpenAPI spec
type CLIGenerator struct {
	Spec      OpenAPI
	Commands  []CLICommand
}

// NewCLIGenerator creates a new CLI generator
func NewCLIGenerator(spec OpenAPI) *CLIGenerator {
	return &CLIGenerator{
		Spec:     spec,
		Commands: extractCommands(spec),
	}
}

// extractCommands extracts CLI commands from OpenAPI spec
func extractCommands(spec OpenAPI) []CLICommand {
	var commands []CLICommand

	// Group operations by tag
	operationsByTag := make(map[string][]struct {
		Method string
		Path   string
		Op     *Operation
	})

	for path, item := range spec.Paths {
		if item.Get != nil {
			tag := getTag(item.Get.Tags)
			operationsByTag[tag] = append(operationsByTag[tag], struct {
				Method string
				Path   string
				Op     *Operation
			}{"GET", path, item.Get})
		}
		if item.Post != nil {
			tag := getTag(item.Post.Tags)
			operationsByTag[tag] = append(operationsByTag[tag], struct {
				Method string
				Path   string
				Op     *Operation
			}{"POST", path, item.Post})
		}
	}

	// Create commands for each tag
	for tag, ops := range operationsByTag {
		cmd := CLICommand{
			Name:   commandName(tag),
			Use:    commandName(tag),
			Short:  tag + " operations",
		}

		// Add subcommands for each operation
		for _, op := range ops {
			subcmd := createSubcommand(op.Method, op.Path, op.Op)
			// Merge flags and args from subcommands
			// For now, we create separate commands
			_ = subcmd
		}

		commands = append(commands, cmd)
	}

	return commands
}

// createSubcommand creates a subcommand from operation
func createSubcommand(method, path string, op *Operation) CLICommand {
	cmd := CLICommand{
		Name:       commandName(op.OperationID),
		Use:        commandName(op.OperationID),
		Short:      op.Summary,
		Long:       op.Summary,
		HTTPMethod: method,
		Path:       path,
	}

	// Extract flags from parameters
	for _, param := range op.Parameters {
		flag := CLIFlag{
			Name:        flagName(param.Name),
			Type:        schemaToFlagType(param.Schema),
			Description: param.Description,
			Required:    param.Required,
		}
		cmd.Flags = append(cmd.Flags, flag)
	}

	// Extract body fields
	if op.RequestBody != nil {
		cmd.HasBody = true
		for contentType, media := range op.RequestBody.Content {
			_ = contentType
			if media.Schema.Properties != nil {
				for name, schema := range media.Schema.Properties {
					field := BodyField{
						Name: flagName(name),
						Type: schemaToFlagType(schema),
					}
					// Check if required
					for _, req := range media.Schema.Required {
						if req == name {
							field.Required = true
							break
						}
					}
					cmd.BodyFields = append(cmd.BodyFields, field)
				}
			}
		}
	}

	return cmd
}

// Generate generates CLI code
func (g *CLIGenerator) Generate(outputPath string) error {
	data := struct {
		Commands []CLICommand
	}{
		Commands: g.Commands,
	}

	return generateFile(outputPath, cliMainTemplate, data)
}

// Helper functions
func getTag(tags []string) string {
	if len(tags) > 0 {
		return tags[0]
	}
	return "default"
}

func commandName(s string) string {
	// Convert operationId to command name
	// listCdrIbs -> list, describeClient -> describe
	s = strings.ToLower(s)
	s = strings.ReplaceAll(s, "_", "-")
	return s
}

func flagName(s string) string {
	// Convert param name to flag name
	// startTime -> start-time
	var result strings.Builder
	for i, r := range s {
		if i > 0 && r >= 'A' && r <= 'Z' {
			result.WriteByte('-')
			result.WriteByte(byte(r - 'A' + 'a'))
		} else {
			result.WriteByte(byte(r))
		}
	}
	return result.String()
}

func schemaToFlagType(schema Schema) string {
	switch schema.Type {
	case "string":
		return "string"
	case "integer":
		return "int"
	case "boolean":
		return "bool"
	default:
		return "string"
	}
}

// Template for generated CLI main
type CLIMainTemplateData struct {
	Commands []CLICommand
}

const cliMainTemplate = `// Code generated by cli_generator.go; DO NOT EDIT.

package main

import (
	"context"
	"fmt"
	"os"
	"time"

	"github.com/raymondtc/clink-cli/pkg/api"
	"github.com/raymondtc/clink-cli/pkg/client"
	"github.com/raymondtc/clink-cli/pkg/renderer"
	"github.com/spf13/cobra"
)

var (
	// Config flags
	accessID     string
	accessSecret string
	baseURL      string
	outputFormat string
)

func main() {
	if err := rootCmd.Execute(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

var rootCmd = &cobra.Command{
	Use:   "clink",
	Short: "天润融通 CLI 工具",
	Long:  "天润融通呼叫中心命令行工具",
}

func init() {
	// Global flags
	rootCmd.PersistentFlags().StringVar(&accessID, "access-id", "", "Access ID (env: CLINK_ACCESS_ID)")
	rootCmd.PersistentFlags().StringVar(&accessSecret, "access-secret", "", "Access Secret (env: CLINK_ACCESS_SECRET)")
	rootCmd.PersistentFlags().StringVar(&baseURL, "base-url", "https://api-sh.clink.cn", "API base URL")
	rootCmd.PersistentFlags().StringVarP(&outputFormat, "output", "o", "table", "Output format: table, json, yaml")

	// Add generated commands
{{range .Commands}}
	rootCmd.AddCommand({{.Name}}Cmd)
{{end}}
}

func createAPI() (*api.GeneratedAPI, error) {
	// Get from env if not provided
	if accessID == "" {
		accessID = os.Getenv("CLINK_ACCESS_ID")
	}
	if accessSecret == "" {
		accessSecret = os.Getenv("CLINK_ACCESS_SECRET")
	}

	if accessID == "" || accessSecret == "" {
		return nil, fmt.Errorf("access-id and access-secret are required")
	}

	config := &client.AuthConfig{
		AccessID:     accessID,
		AccessSecret: accessSecret,
	}

	return api.NewGeneratedAPI(baseURL, config)
}

func getRenderer() *renderer.Renderer {
	return renderer.New(renderer.Format(outputFormat))
}

{{range .Commands}}
var {{.Name}}Cmd = &cobra.Command{
	Use:   "{{.Use}}",
	Short: "{{.Short}}",
	RunE: func(cmd *cobra.Command, args []string) error {
		// Implementation will be generated
		return nil
	},
}

func init() {
{{range .Flags}}
	{{.Name}}Cmd.Flags().{{.Type}}("{{.Name}}", {{.Default}}, "{{.Description}}")
{{end}}
}
{{end}}
`

// generateFile generates a file from template
func generateFile(filename, tmplStr string, data interface{}) error {
	tmpl, err := template.New(filepath.Base(filename)).Parse(tmplStr)
	if err != nil {
		return fmt.Errorf("parse template: %w", err)
	}

	file, err := os.Create(filename)
	if err != nil {
		return fmt.Errorf("create file: %w", err)
	}
	defer file.Close()

	if err := tmpl.Execute(file, data); err != nil {
		return fmt.Errorf("execute template: %w", err)
	}

	return nil
}

// GenerateCLICommands generates full CLI commands from OpenAPI spec
func GenerateCLICommands(specPath string) error {
	data, err := os.ReadFile(specPath)
	if err != nil {
		return fmt.Errorf("read spec: %w", err)
	}

	var spec OpenAPI
	if err := yaml.Unmarshal(data, &spec); err != nil {
		return fmt.Errorf("parse spec: %w", err)
	}

	// Generate command files
	commands := []struct {
		Tag  string
		Name string
	}{
		{"CallRecords", "records"},
		{"AgentStatus", "agents"},
		{"CallControl", "call"},
		{"Queue", "queue"},
	}

	for _, cmd := range commands {
		if err := generateCommandFile(spec, cmd.Tag, cmd.Name); err != nil {
			return fmt.Errorf("generate %s: %w", cmd.Name, err)
		}
	}

	return nil
}

// generateCommandFile generates a single command file
func generateCommandFile(spec OpenAPI, tag, name string) error {
	data := CommandFileData{
		Package: "main",
		Name:    name,
	}

	// Find operations for this tag
	for path, item := range spec.Paths {
		if item.Get != nil && hasTag(item.Get.Tags, tag) {
			op := OperationInfo{
				Name:       operationToCmdName(item.Get.OperationID),
				HTTPMethod: "GET",
				Path:       path,
				Summary:    item.Get.Summary,
			}
			for _, p := range item.Get.Parameters {
				op.Flags = append(op.Flags, FlagInfo{
					Name:        flagName(p.Name),
					Type:        schemaToFlagType(p.Schema),
					Description: p.Description,
					Required:    p.Required,
				})
			}
			data.Operations = append(data.Operations, op)
		}
		if item.Post != nil && hasTag(item.Post.Tags, tag) {
			op := OperationInfo{
				Name:       operationToCmdName(item.Post.OperationID),
				HTTPMethod: "POST",
				Path:       path,
				Summary:    item.Post.Summary,
			}
			if item.Post.RequestBody != nil {
				for contentType, media := range item.Post.RequestBody.Content {
					_ = contentType
					if media.Schema.Properties != nil {
						for fname, schema := range media.Schema.Properties {
							op.Flags = append(op.Flags, FlagInfo{
								Name:        flagName(fname),
								Type:        schemaToFlagType(schema),
								Description: fname,
								Required:    isRequired(fname, media.Schema.Required),
							})
						}
					}
				}
			}
			data.Operations = append(data.Operations, op)
		}
	}

	filename := fmt.Sprintf("cmd/clink/%s_gen.go", name)
	return generateFileFromTemplate(filename, commandFileTemplate, data)
}

// CommandFileData holds data for command file template
type CommandFileData struct {
	Package    string
	Name       string
	Operations []OperationInfo
}

// OperationInfo holds operation info
type OperationInfo struct {
	Name       string
	HTTPMethod string
	Path       string
	Summary    string
	Flags      []FlagInfo
}

// FlagInfo holds flag info
type FlagInfo struct {
	Name        string
	Type        string
	Description string
	Required    bool
	Default     string
}

// operationToCmdName converts operationId to command name
func operationToCmdName(opID string) string {
	// listCdrIbs -> list
	// getAgentStatus -> status
	parts := []string{
		"list", "get", "describe", "create", "update", "delete",
		"online", "offline", "pause", "unpause", "make", "webcall",
	}

	lower := strings.ToLower(opID)
	for _, p := range parts {
		if strings.HasPrefix(lower, p) {
			return p
		}
	}

	// Default: use first word
	for i, r := range opID {
		if i > 0 && r >= 'A' && r <= 'Z' {
			return strings.ToLower(opID[:i])
		}
	}
	return strings.ToLower(opID)
}

func hasTag(tags []string, tag string) bool {
	for _, t := range tags {
		if t == tag {
			return true
		}
	}
	return false
}

func isRequired(field string, required []string) bool {
	for _, r := range required {
		if r == field {
			return true
		}
	}
	return false
}

const commandFileTemplate = `// Code generated from OpenAPI spec; DO NOT EDIT.

package main

import (
	"github.com/spf13/cobra"
)

func init() {
{{range .Operations}}
	{{$.Name}}Cmd.AddCommand({{.Name}}Cmd)
{{end}}
}

{{range .Operations}}
var {{.Name}}Cmd = &cobra.Command{
	Use:   "{{.Name}}{{if eq .HTTPMethod \"GET\"}} [flags]{{end}}",
	Short: "{{.Summary}}",
	RunE:  run{{.Name | title}},
}

func init() {
{{range .Flags}}
	{{.Name}}Cmd.Flags().{{flagTypeToFunc .Type}}("{{.Name}}", "{{.Default}}", "{{.Description}}")
{{if .Required}}
	{{.Name}}Cmd.MarkFlagRequired("{{.Name}}")
{{end}}
{{end}}
}
{{end}}
`

func generateFileFromTemplate(filename, tmplStr string, data interface{}) error {
	funcMap := template.FuncMap{
		"title": strings.Title,
		"flagTypeToFunc": func(t string) string {
			switch t {
			case "int":
				return "Int"
			case "bool":
				return "Bool"
			default:
				return "String"
			}
		},
	}

	tmpl, err := template.New(filepath.Base(filename)).Funcs(funcMap).Parse(tmplStr)
	if err != nil {
		return fmt.Errorf("parse template: %w", err)
	}

	file, err := os.Create(filename)
	if err != nil {
		return fmt.Errorf("create file: %w", err)
	}
	defer file.Close()

	if err := tmpl.Execute(file, data); err != nil {
		return fmt.Errorf("execute template: %w", err)
	}

	return nil
}
